// AUTO-GENERATED by scripts/publish-tenant.ts — 직접 수정하지 마세요.
import type { QuestionBank } from './store.js';
import type { QuestionRepeatAnalysis } from './types.js';
import bank_avonhotel from '../src/data/live-avonhotel-question-bank.json' with { type: 'json' };
import analyses_avonhotel from '../src/data/live-avonhotel-question-analyses.json' with { type: 'json' };
import bank_banobagi from '../src/data/live-banobagi-question-bank.json' with { type: 'json' };
import analyses_banobagi from '../src/data/live-banobagi-question-analyses.json' with { type: 'json' };
import bank_bkhospital from '../src/data/live-bkhospital-question-bank.json' with { type: 'json' };
import analyses_bkhospital from '../src/data/live-bkhospital-question-analyses.json' with { type: 'json' };
import bank_bymeps from '../src/data/live-bymeps-question-bank.json' with { type: 'json' };
import analyses_bymeps from '../src/data/live-bymeps-question-analyses.json' with { type: 'json' };
import bank_daprs from '../src/data/live-daprs-question-bank.json' with { type: 'json' };
import analyses_daprs from '../src/data/live-daprs-question-analyses.json' with { type: 'json' };
import bank_girinps from '../src/data/live-girinps-question-bank.json' with { type: 'json' };
import analyses_girinps from '../src/data/live-girinps-question-analyses.json' with { type: 'json' };
import bank_gunsanhotel from '../src/data/live-gunsanhotel-question-bank.json' with { type: 'json' };
import analyses_gunsanhotel from '../src/data/live-gunsanhotel-question-analyses.json' with { type: 'json' };
import bank_gunsanstayhotel from '../src/data/live-gunsanstayhotel-question-bank.json' with { type: 'json' };
import analyses_gunsanstayhotel from '../src/data/live-gunsanstayhotel-question-analyses.json' with { type: 'json' };
import bank_h_eunpapalace from '../src/data/live-h-eunpapalace-question-bank.json' with { type: 'json' };
import analyses_h_eunpapalace from '../src/data/live-h-eunpapalace-question-analyses.json' with { type: 'json' };
import bank_idhospital from '../src/data/live-idhospital-question-bank.json' with { type: 'json' };
import analyses_idhospital from '../src/data/live-idhospital-question-analyses.json' with { type: 'json' };
import bank_k_wonjin from '../src/data/live-k-wonjin-question-bank.json' with { type: 'json' };
import analyses_k_wonjin from '../src/data/live-k-wonjin-question-analyses.json' with { type: 'json' };
import bank_ramadagunsan from '../src/data/live-ramadagunsan-question-bank.json' with { type: 'json' };
import analyses_ramadagunsan from '../src/data/live-ramadagunsan-question-analyses.json' with { type: 'json' };
import bank_sm_ps from '../src/data/live-sm-ps-question-bank.json' with { type: 'json' };
import analyses_sm_ps from '../src/data/live-sm-ps-question-analyses.json' with { type: 'json' };
import bank_vvlyps from '../src/data/live-vvlyps-question-bank.json' with { type: 'json' };
import analyses_vvlyps from '../src/data/live-vvlyps-question-analyses.json' with { type: 'json' };
import bank_yunoprs from '../src/data/live-yunoprs-question-bank.json' with { type: 'json' };
import analyses_yunoprs from '../src/data/live-yunoprs-question-analyses.json' with { type: 'json' };

export interface LiveAnalysesFile {
  tenantId: string;
  weekOf: string;
  analyses: QuestionRepeatAnalysis[];
}

export const LIVE_BANKS: Record<string, QuestionBank> = {
  'avonhotel': bank_avonhotel as QuestionBank,
  'banobagi': bank_banobagi as QuestionBank,
  'bkhospital': bank_bkhospital as QuestionBank,
  'bymeps': bank_bymeps as QuestionBank,
  'daprs': bank_daprs as QuestionBank,
  'girinps': bank_girinps as QuestionBank,
  'gunsanhotel': bank_gunsanhotel as QuestionBank,
  'gunsanstayhotel': bank_gunsanstayhotel as QuestionBank,
  'h-eunpapalace': bank_h_eunpapalace as QuestionBank,
  'idhospital': bank_idhospital as QuestionBank,
  'k-wonjin': bank_k_wonjin as QuestionBank,
  'ramadagunsan': bank_ramadagunsan as QuestionBank,
  'sm-ps': bank_sm_ps as QuestionBank,
  'vvlyps': bank_vvlyps as QuestionBank,
  'yunoprs': bank_yunoprs as QuestionBank,
};

export const LIVE_ANALYSES: LiveAnalysesFile[] = [
  analyses_avonhotel as LiveAnalysesFile,
  analyses_banobagi as LiveAnalysesFile,
  analyses_bkhospital as LiveAnalysesFile,
  analyses_bymeps as LiveAnalysesFile,
  analyses_daprs as LiveAnalysesFile,
  analyses_girinps as LiveAnalysesFile,
  analyses_gunsanhotel as LiveAnalysesFile,
  analyses_gunsanstayhotel as LiveAnalysesFile,
  analyses_h_eunpapalace as LiveAnalysesFile,
  analyses_idhospital as LiveAnalysesFile,
  analyses_k_wonjin as LiveAnalysesFile,
  analyses_ramadagunsan as LiveAnalysesFile,
  analyses_sm_ps as LiveAnalysesFile,
  analyses_vvlyps as LiveAnalysesFile,
  analyses_yunoprs as LiveAnalysesFile,
];
