// AUTO-GENERATED by scripts/publish-tenant.ts — 직접 수정하지 마세요.
import type { QuestionBank } from './store.js';
import type { QuestionRepeatAnalysis } from './types.js';
import bank_hdmpension from '../src/data/live-hdmpension-question-bank.json' with { type: 'json' };
import analyses_hdmpension from '../src/data/live-hdmpension-question-analyses.json' with { type: 'json' };
import bank_example_brand from '../src/data/live-question-bank.json' with { type: 'json' };
import analyses_example_brand from '../src/data/live-question-analyses.json' with { type: 'json' };
import bank_stay_meomum from '../src/data/live-stay-question-bank.json' with { type: 'json' };
import analyses_stay_meomum from '../src/data/live-stay-question-analyses.json' with { type: 'json' };

export interface LiveAnalysesFile {
  tenantId: string;
  weekOf: string;
  analyses: QuestionRepeatAnalysis[];
}

export const LIVE_BANKS: Record<string, QuestionBank> = {
  'hdmpension': bank_hdmpension as QuestionBank,
  'example-brand': bank_example_brand as QuestionBank,
  'stay-meomum': bank_stay_meomum as QuestionBank,
};

export const LIVE_ANALYSES: LiveAnalysesFile[] = [
  analyses_hdmpension as LiveAnalysesFile,
  analyses_example_brand as LiveAnalysesFile,
  analyses_stay_meomum as LiveAnalysesFile,
];
