// AUTO-GENERATED by scripts/publish-tenant.ts — 직접 수정하지 마세요.
import type { QuestionBank } from './store.js';
import type { QuestionRepeatAnalysis } from './types.js';
import bank_k_wonjin from '../src/data/live-k-wonjin-question-bank.json' with { type: 'json' };
import analyses_k_wonjin from '../src/data/live-k-wonjin-question-analyses.json' with { type: 'json' };

export interface LiveAnalysesFile {
  tenantId: string;
  weekOf: string;
  analyses: QuestionRepeatAnalysis[];
}

export const LIVE_BANKS: Record<string, QuestionBank> = {
  'k-wonjin': bank_k_wonjin as QuestionBank,
};

export const LIVE_ANALYSES: LiveAnalysesFile[] = [
  analyses_k_wonjin as LiveAnalysesFile,
];
