/**
 * 로컬에서 등록·측정한 브랜드(data/<id>/)를 배포용 src/data로 baking하고,
 * demoData가 읽는 정적 레지스트리(server/liveRegistry.ts)를 자동 생성한다.
 *   npx tsx scripts/publish-tenant.ts <tenantId>   # 한 브랜드 배포 반영
 *   npx tsx scripts/publish-tenant.ts              # 레지스트리만 재생성
 * 이후 git commit + npx vercel --prod 로 공개된다.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { loadTenants } from '../server/config'
import { computeCohortRank } from '../server/scoring'
import type { WeeklyScorecard } from '../src/prompts/b8-report'

const SRC = 'src/data'
const REGISTRY = 'server/liveRegistry.ts'
// 이 두 시드 브랜드는 기존 파일명(live-question-*, live-stay-question-*)과 재계산 스크립트를 쓴다.
const SEED_TENANTS = new Set(['example-brand', 'stay-meomum'])

const read = <T,>(p: string): T => JSON.parse(readFileSync(p, 'utf8')) as T
const sanitize = (id: string): string => id.replace(/[^a-zA-Z0-9]/g, '_')

/** src/data의 live-*-question-analyses.json을 훑어 정적 import 레지스트리를 다시 만든다. */
function regenerateRegistry(): string[] {
  const analysesFiles = readdirSync(SRC).filter((f) => /^live-.*question-analyses\.json$/.test(f))
  const seen = new Set<string>()
  const entries: { tenantId: string; bankFile: string; analysesFile: string; v: string }[] = []
  for (const analysesFile of analysesFiles.sort()) {
    const bankFile = analysesFile.replace('question-analyses', 'question-bank')
    if (!existsSync(`${SRC}/${bankFile}`)) continue
    const tenantId = read<{ tenantId?: string }>(`${SRC}/${analysesFile}`).tenantId
    if (!tenantId || seen.has(tenantId)) {
      if (tenantId) console.warn(`[registry] tenantId 중복 무시: ${tenantId} (${analysesFile})`)
      continue
    }
    seen.add(tenantId)
    entries.push({ tenantId, bankFile, analysesFile, v: sanitize(tenantId) })
  }

  const imports = entries
    .flatMap((e) => [
      `import bank_${e.v} from '../src/data/${e.bankFile}' with { type: 'json' };`,
      `import analyses_${e.v} from '../src/data/${e.analysesFile}' with { type: 'json' };`,
    ])
    .join('\n')
  const banks = entries.map((e) => `  '${e.tenantId}': bank_${e.v} as QuestionBank,`).join('\n')
  const analyses = entries.map((e) => `  analyses_${e.v} as LiveAnalysesFile,`).join('\n')

  const content = `// AUTO-GENERATED by scripts/publish-tenant.ts — 직접 수정하지 마세요.
import type { QuestionBank } from './store.js';
import type { QuestionRepeatAnalysis } from './types.js';
${imports}

export interface LiveAnalysesFile {
  tenantId: string;
  weekOf: string;
  analyses: QuestionRepeatAnalysis[];
}

export const LIVE_BANKS: Record<string, QuestionBank> = {
${banks}
};

export const LIVE_ANALYSES: LiveAnalysesFile[] = [
${analyses}
];
`
  writeFileSync(REGISTRY, content)
  return entries.map((e) => e.tenantId)
}

/** data/<id> 측정 결과를 src/data로 baking하고 스코어카드·코호트 순위를 갱신한다. */
async function bakeTenant(tenantId: string): Promise<{ weekOf: string; score: number }> {
  if (SEED_TENANTS.has(tenantId)) {
    throw new Error(
      `${tenantId}는 시드 브랜드입니다 — publish-tenant 대신 rescore-all/recompute-stay-scorecard로 반영하세요.`,
    )
  }
  const tenant = (await loadTenants()).find((t) => t.tenantId === tenantId)
  if (!tenant) throw new Error(`tenants.config.json에 없는 tenantId: ${tenantId} (먼저 등록·측정하세요)`)

  const histPath = `data/${tenantId}/scorecard-history.json`
  if (!existsSync(histPath)) throw new Error(`측정 결과가 없습니다: ${histPath} (로컬에서 등록·측정 먼저)`)
  const hist = read<WeeklyScorecard[]>(histPath)
  const card = hist[hist.length - 1]
  const weekOf = card.weekOf

  const bankPath = `data/${tenantId}/question-bank/${tenant.questionBankVersion}.json`
  const anPath = `data/${tenantId}/${weekOf}/question-analyses.json`
  if (!existsSync(bankPath) || !existsSync(anPath)) {
    throw new Error(`측정 산출물 누락: ${existsSync(bankPath) ? anPath : bankPath}`)
  }

  writeFileSync(`${SRC}/live-${tenantId}-question-bank.json`, JSON.stringify(read(bankPath), null, 2) + '\n')
  const analyses = read(anPath)
  writeFileSync(
    `${SRC}/live-${tenantId}-question-analyses.json`,
    JSON.stringify({ tenantId, weekOf, analyses }, null, 2) + '\n',
  )

  const cardsPath = `${SRC}/demo-scorecards.json`
  const cards = read<WeeklyScorecard[]>(cardsPath).filter(
    (c) => !(c.tenantId === tenantId && c.weekOf === weekOf),
  )
  cards.push(card)
  for (const c of cards) {
    const group = cards.filter((x) => x.industry === c.industry && x.region === c.region && x.weekOf === c.weekOf)
    c.cohortRank = computeCohortRank(c.aeoScore.current, group)
  }
  writeFileSync(cardsPath, JSON.stringify(cards, null, 2) + '\n')

  return { weekOf, score: card.aeoScore.current }
}

async function main(): Promise<void> {
  const tenantId = process.argv[2]
  if (!tenantId) {
    const ids = regenerateRegistry()
    console.log(`[registry] 재생성 완료 (${ids.length}개): ${ids.join(', ')}`)
    return
  }
  const { weekOf, score } = await bakeTenant(tenantId)
  const ids = regenerateRegistry()
  console.log(`✓ ${tenantId} 배포 반영 준비 완료 — ${weekOf}, AEO Score ${score}`)
  console.log(`[registry] ${ids.length}개: ${ids.join(', ')}`)
  console.log('다음: git add -A && git commit -m "data: publish ' + tenantId + '" && npx vercel --prod')
}

void main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exitCode = 1
})
